### ISSUE TITLE
Eroare conexiune

### ISSUE THREAD

**Issue by popadaniel72** [infoeducatie/infoeducatie-android#17]
Am instalat aplicatia pe Nexus 7(Android 5.1.1) si la pornire afiseaza Eroare de conexiune, iar cele 3 valori afisate sunt 0. Conexiunea la internet este prin wireless(UPC).

**Comment by robertdxyz** [comment]
Asa zice si la mine

**Comment by boldijar** [comment]
multumesc, maine voi remedia, probabil din cauza unor mici schimbari la API

**Comment by boldijar** [comment]
https://github.com/infoeducatie/infoeducatie-android/pull/18

**Comment by boldijar** [comment]
rezolvat, va fi publicat pe google play update-ul dupa ce vor adauga posibilitatea de a afisa si proiectele in parte cu detalii suplimentare
