### ISSUE TITLE
URL API

### ISSUE THREAD

**Issue by robertdxyz** [infoeducatie/infoeducatie-android#9]
URL-ul apare in 2 locuri diferite. Cand vrei sa il modifici trebuie sa modifici in 2 locuri si nu e ok.
De asemenea trebuie sa fie URL diferit in productie si development. Pentru a diferentia poti folosi.

```
if (BuildConfig.DEBUG)
```

Te rog sa faci modificarile astea pe un branch nou si sau faci pull request pentru review.

https://github.com/infoeducatie/infoeducatie-android/blob/457b74793e0329d443ce4b1b0e7c1500db46de9b/app/src/main/java/com/infoeducatie/app/service/management/EditionManagement.java#L17

https://github.com/infoeducatie/infoeducatie-android/blob/457b74793e0329d443ce4b1b0e7c1500db46de9b/app/src/main/java/com/infoeducatie/app/service/management/ProjectsManagement.java#L67

https://github.com/infoeducatie/infoeducatie-android/blob/457b74793e0329d443ce4b1b0e7c1500db46de9b/app/src/main/java/com/infoeducatie/app/service/ServiceLocator.java#L10

**Comment by boldijar** [comment]
done, pana la urma cu BuildConfig
